### ISSUE TITLE
Include a new column with total downloads badges in the board

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/dashboard#11]
Currently, we have a column with raw (as opposed to a badge of) download counts from the last week.

Additionally, it will be good to have a new column with badges for total download counts since the initial CRAN release.

**Comment by etiennebacher** [comment]
Is it useful to have the number of downloads in the last week? I think adding another badge with total counts will clutter the table

**Comment by IndrajeetPatil** [comment]
> Is it useful to have the number of downloads in the last week?

I am happy to leave it out.

But you can comment out - and not remove - the relevant code, just in case if we change our minds.

**Comment by etiennebacher** [comment]
Done in [2709fe9](https://github.com/easystats/dashboard/commit/2709fe9a2b1d798ce4abb74b557adc9996e774fa)
