### ISSUE TITLE
Change the account that commits the updated dashboard

### ISSUE THREAD

**Issue by etiennebacher** [easystats/dashboard#12]
I got this message:

![image](https://user-images.githubusercontent.com/52219252/222129307-6d5711ea-4085-42d3-b72a-49896431bce0.png)

My usage will reset on April 1, 2023. I guess this is because my account commits the updated dashboard 3-4 times a day, need to check if there's a way to use easystats account to do this

**Comment by rempsyc** [comment]
I have GitHub Pro, I suppose it comes with higher limits, is there a way for me to use my account?

**Comment by etiennebacher** [comment]
I remember I tried a bit before to change the account but I couldn't make it work. I just noticed this line:

https://github.com/easystats/dashboard/blob/fb21c06a41da25ea3a1948b6e52b40c4bc96242f/.github/workflows/render-rmarkdown.yaml#L45

Maybe using `secrets.PAT_DASHBOARD` instead will make it work. I'll check

**Comment by rempsyc** [comment]
Yeah that would make senes

**Comment by etiennebacher** [comment]
Doesn't seem to work:
https://github.com/easystats/dashboard/actions/runs/5772373932/job/15647287746#step:7:86

**Comment by rempsyc** [comment]
Did you make secrets.PAT_DASHBOARD? Or was it already there?

**Comment by etiennebacher** [comment]
I made it but I can't remember if it was with my github account or easystats'

**Comment by rempsyc** [comment]
Ok gimme a second I'll try something

**Comment by rempsyc** [comment]
It doesn't allow me to change the file directly on GitHub. Can you change it to this: `secrets.REM_DASHBOARD`

**Comment by rempsyc** [comment]
Not sure it's going to change the rate limit though because when creating the environment variable, it doesn't allow me to select easystats repositories with my personal account, it first asks me to switch to the easystats account. This might be a tactic to encourage project users to pay for a paid team account... That might be why we may not "change the account" for this workflow.

There is also more info about this workflow here: https://github.com/peaceiris/actions-gh-pages

In particular, 

> For newbies of GitHub Actions: Note that the GITHUB_TOKEN is NOT a personal access token. A GitHub Actions runner automatically creates a GITHUB_TOKEN secret to authenticate in your workflow. So, you can start to deploy immediately without any configuration. Notes: Actually, the GITHUB_TOKEN works for deploying to GitHub Pages but it has still some limitations.

**Comment by etiennebacher** [comment]
> Can you change it to this: `secrets.REM_DASHBOARD`

In the CI or in the secrets (in the repo settings)?

**Comment by rempsyc** [comment]
In the workflow file: https://github.com/easystats/dashboard/blob/fb21c06a41da25ea3a1948b6e52b40c4bc96242f/.github/workflows/render-rmarkdown.yaml#L45

**Comment by etiennebacher** [comment]
Looks like it worked, you appear as the commit author here: https://github.com/easystats/dashboard/actions/runs/5772499654
You might receive some notifications of build failure from time to time. 

Thanks for reviving this issue! We could try to revert the hack I made on the PR tab, but I won't look at it today ;)

**Comment by rempsyc** [comment]
Ok great! No rush for the #13 :)
