### ISSUE TITLE
Dashboard is not being rendering on schedule

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/dashboard#21]
I am guessing this is due to the token issue.

Note that I have already disabled the problematic workflow status related tab. So that can't be the issue.

**Comment by etiennebacher** [comment]
Looks like https://github.com/easystats/dashboard/commit/d110886c4d3cd168afaf77250b96d4ba468df170 fixed it

**Comment by IndrajeetPatil** [comment]
Thanks!!
