### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/dashboard#8]
To be consistent with other repos in the organization.

**Comment by etiennebacher** [comment]
@IndrajeetPatil I created a branch "main" that is equal to "master" but I don't have the rights to change the default branch in this repo, can you do it?

**Comment by IndrajeetPatil** [comment]
Done!

**Comment by IndrajeetPatil** [comment]
I have also made you admin for this repo.

**Comment by etiennebacher** [comment]
Thanks
